using System;
using System.Collections.Generic;
using VoxelEngine.Graphics;

namespace VoxelEngine.Rendering.FrameGraphDesign;

/// <summary>
/// 1. Resource Handle (Instead of Strings!)
/// We do NOT use raw strings for dictionaries because string comparison is slow and allocates memory.
/// Instead, we use a lightweight struct wrapping an integer ID, usually generated by hashing a string (like "GBuffer_Albedo") once.
/// </summary>
public readonly record struct FGResourceHandle(int Id);

/// <summary>
/// A helper to hash strings into integers.
/// </summary>
public static class StringID
{
    // A simple hash function (e.g. FNV-1a)
    public static int Hash(string text) => text.GetHashCode(); // Using builtin hash for simplicity
}

/// <summary>
/// 2. The Pass Interface
/// </summary>
public interface IFrameGraphPass
{
    string Name { get; }
    
    // Called once before rendering to declare dependencies
    void Setup(FrameGraphBuilder builder);
    
    // Called during rendering to actually execute graphics commands
    void Execute(FrameGraphContext context, IGraphicsCommandsList cmdList);
}

/// <summary>
/// 3. The Builder
/// Passes use this during Setup() to request resources and declare reads/writes.
/// </summary>
public sealed class FrameGraphBuilder
{
    // Internal data collected by the builder
    internal List<FGResourceHandle> Reads = new();
    internal List<FGResourceHandle> Writes = new();
    internal List<FGResourceHandle> Creates = new();

    /// <summary>
    /// Tells the graph to create a transient texture for this frame.
    /// </summary>
    public FGResourceHandle CreateTexture(string name /* format, width, height... */)
    {
        int id = StringID.Hash(name);
        var handle = new FGResourceHandle(id);
        
        Creates.Add(handle); // We are creating it
        Writes.Add(handle);  // Creating implies we are writing to it initially
        
        // The graph would store the format/size metadata here too!
        
        return handle;
    }

    /// <summary>
    /// Declares that the pass will READ from this resource.
    /// This forces this pass to execute AFTER whatever pass wrote to it!
    /// </summary>
    public FGResourceHandle Read(string name)
    {
        var handle = new FGResourceHandle(StringID.Hash(name));
        Reads.Add(handle);
        return handle;
    }

    /// <summary>
    /// Declares that the pass will WRITE to an existing resource.
    /// </summary>
    public FGResourceHandle Write(string name)
    {
        var handle = new FGResourceHandle(StringID.Hash(name));
        Writes.Add(handle);
        return handle;
    }
}

/// <summary>
/// 4. The Context
/// Passed to Execute() so the pass can get the physical RenderTargets the Graph created.
/// </summary>
public sealed class FrameGraphContext
{
    // In a real engine, this maps the abstract FGResourceHandle (Id) to the physical RenderTargetHandle
    public RenderTargetHandle GetPhysicalRenderTarget(FGResourceHandle handle)
    {
        // Mock returning a physical handle
        return default; 
    }
}

/// <summary>
/// 5. The Main FrameGraph Engine
/// </summary>
public sealed class FrameGraph
{
    private class PassNode
    {
        public IFrameGraphPass Pass;
        public FrameGraphBuilder Builder = new();
        public List<PassNode> Dependencies = new(); // Passes that MUST run before this one
    }

    private readonly List<PassNode> _nodes = new();
    private readonly List<PassNode> _sortedNodes = new();

    public void AddPass(IFrameGraphPass pass)
    {
        _nodes.Add(new PassNode { Pass = pass });
    }

    /// <summary>
    /// The Magic! Builds the graph, figures out execution order, and allocates resources.
    /// </summary>
    public void Compile()
    {
        _sortedNodes.Clear();

        // Step 1: Run Setup() on all passes to collect their grocery lists (Reads/Writes)
        foreach (var node in _nodes)
        {
            node.Builder = new FrameGraphBuilder();
            node.Pass.Setup(node.Builder);
        }

        // Step 2: Build Dependencies
        // If Node A writes to a texture, and Node B reads from it... Node B depends on Node A.
        foreach (var nodeA in _nodes)
        {
            foreach (var nodeB in _nodes)
            {
                if (nodeA == nodeB) continue;

                // Check if Node B reads something Node A writes
                foreach (var readHandle in nodeB.Builder.Reads)
                {
                    if (nodeA.Builder.Writes.Contains(readHandle))
                    {
                        // Node B MUST run after Node A!
                        nodeB.Dependencies.Add(nodeA);
                    }
                }
            }
        }

        // Step 3: Topological Sort (Determine final execution order)
        // This is a standard algorithm to sort connected items without violating dependencies.
        var visited = new HashSet<PassNode>();
        foreach (var node in _nodes)
        {
            VisitNode(node, visited, _sortedNodes);
        }

        // Step 4: Allocate Physical Resources 
        // The real graph would now create the actual ID3D12/Vulkan Textures and RenderTargets
        // because it knows exactly the lifespan of every texture!
    }

    private void VisitNode(PassNode node, HashSet<PassNode> visited, List<PassNode> sorted)
    {
        if (visited.Contains(node)) return;

        // Visit dependencies first! (So they are added to the list BEFORE this node)
        foreach (var dep in node.Dependencies)
        {
            VisitNode(dep, visited, sorted);
        }

        visited.Add(node);
        sorted.Add(node); // Finally, add this node
    }

    /// <summary>
    /// Executes the correctly sorted graph.
    /// </summary>
    public void Execute(IGraphicsDevice device)
    {
        var context = new FrameGraphContext();
        var commandLists = new List<IGraphicsCommandsList>();

        // We iterate over the topologically sorted list!
        foreach (var node in _sortedNodes)
        {
            // E.g. get a command list from a pool
            // var cmd = device.Factory.CreateGraphicsCommandsList(); 
            // node.Pass.Execute(context, cmd);
            // commandLists.Add(cmd);
        }

        // device.Submit(commandLists.ToArray());
    }
}
